spring.application.name=cinema-booking-api
#kích hoạt profile dev khi chạy local
spring.profiles.active=dev

#cấu hình đường dẫn swagger ui với openapi docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html